### ISSUE TITLE
Tasks-Month-CashFlow-AAU RealTime no funciona

### ISSUE THREAD

**Issue by rianby64** [m3co/arca-redux#5]
Eso esta dando errores. Hay que simplemente dejar de utilizar RealTime para esta vista. Hasta nueva orden. Pasando a `APU-ImportSupplies`.

**Comment by rianby64** [comment]
`APU-ImportSupplies` es de @NovikovAntonY

**Comment by anovikau** [comment]
@rianby64  думаю можно закрыть, не актуален баг

**Comment by rianby64** [comment]
Спасибо
