### ISSUE TITLE
Price может быть нулевым

### ISSUE THREAD

**Issue by NovikovAntonY** [m3co/arca-redux#7]
pq: new row for relation `"_APU"` violates check constraint `"_APU_Price_check"`

При удалении снабжения.

**Comment by rianby64** [comment]
На самом деле, `Price > 0` и если суждено чтобы не было никаких `Supplies` то по логике вещей, получается `Price = null`.

**Comment by rianby64** [comment]
![image](https://user-images.githubusercontent.com/25993/72223446-e5c17100-357f-11ea-9546-6609bdac5fa8.png)

**Comment by rianby64** [comment]
Обновил сервак! все работает!
