### ISSUE TITLE
Удалить пустую строку APU-Import-Supplies

### ISSUE THREAD

**Issue by NovikovAntonY** [m3co/arca-redux#8]
Для каждого `APUID` сущевствует пустая строка, она лишняя. Для вставки информации у нас есть `Insert`.

**Comment by rianby64** [comment]
![image](https://user-images.githubusercontent.com/25993/72223452-f07c0600-357f-11ea-9e1a-52c4725b7bbc.png)

**Comment by rianby64** [comment]
Обновил сервак! все работает!
